<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>genGutoITAU</name>
  <uuid>0de6c5f6-f89f-49c3-86c6-b14b7acd3b63</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to the input token count of 'ML model invocation' ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
