<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>genGutoITAU</name>
  <uuid>06aa7ad2-1ad7-4330-b490-41e7aa99eccd</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to a new ML model input where
		the topic is topic , 
		the variable 2 is 'variable 2' ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
